import '../styles/globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import GlobalLayout from '@/layouts/GlobalLayout';
import dynamic from 'next/dynamic';

const Ellipses = dynamic(() => import('@/components/toolbox/Ellipses'), { ssr: false });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <html lang="en">
   <body className={inter.className}>
    <main className="flex min-h-screen w-full relative">
     <Ellipses />
     <GlobalLayout>{children}</GlobalLayout>
    </main>
   </body>
  </html>
 );
}
